pipeline {
    agent any

    environment {
        NODEJS_HOME = "C:\\Program Files\\nodejs"
        PATH = "${NODEJS_HOME}:${env.PATH}"
    }

    stages {
        stage('Cloner le code') {
            steps {
                git branch: 'main', url: 'https://github.com/Cyril-lavoisier/Projet-Potager.git'
            }
        }
        
        stage('Installer les dépendances') {
            steps {
                dir('C:\\Users\\Cyril\\Desktop\\Projet-Potager\\projet-potager') { // Remplace par le bon chemin si nécessaire
                    sh 'npm install --legacy-peer-deps'
                }
            }
        }
    /*
        stage('Tester l\'application') {
            steps {
                dir('C:\\Users\\Cyril\\Desktop\\Projet-Potager\\projet-potager') {
                    sh 'npm test'
                }
            }
        }
*/
        stage('Build frontend') {
            steps {
                sh 'npm run build' // Adapter la commande si nécessaire
            }
        }

        stage('Déploiement du backend') {
            steps {
                sh '''
                pm2 stop all || true
                pm2 start server.js --name projet-potager
                '''
            }
        }

        stage('Nettoyage') {
            steps {
                cleanWs()
            }
        }
    }

    post {
        always {
            echo 'Pipeline terminé'
        }
        failure {
            echo 'Le pipeline a échoué'
        }
    }
}